[".config/zsh/plugins/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git"
    refreshPeriod = "168h"
[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"